-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.roles
(
    rol_id serial NOT NULL,
    name character varying(20) COLLATE pg_catalog."default" NOT NULL,
    active boolean NOT NULL DEFAULT true,
    CONSTRAINT roles_pkey PRIMARY KEY (rol_id),
    CONSTRAINT name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.users
(
    user_id integer GENERATED ALWAYS AS IDENTITY,
    rol_id integer NOT NULL,
    frist_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    email character varying(100) NOT NULL,
    password text NOT NULL,
    active boolean NOT NULL DEFAULT TRUE,
    created_at timestamp with time zone NOT NULL DEFAULT DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id),
    CONSTRAINT email UNIQUE (email)
);

ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT roles FOREIGN KEY (rol_id)
    REFERENCES public.roles (rol_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;